# Generated by Django 3.1.4 on 2020-12-29 17:25

from django.contrib.auth.models import User
from django.db import migrations
from ..models import Anecdote

def populate_db(apps, schema_editor):
    mikke = User.objects.create_user('mikke', 'mikke@kukkuu.cs', 'mikkepw')
    jakke = User.objects.create_user('jakke', 'jakke@kukkuu.cs', 'jakkepw')

    anecdote = Anecdote(owner=mikke, anecdote_text='In the land of the blind, the man with the whiskers is king')
    


class Migration(migrations.Migration):

    dependencies = [
        ('anecdotes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
